ARG PHP_VERSION
FROM php:$PHP_VERSION

RUN apk add --no-cache $PHPIZE_DEPS

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer creates=/usr/local/bin/composer warn=no

RUN pecl install xdebug

WORKDIR /var/www/html/auth