version: "3.9"

services:
  api_db:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile-apidb
      args:
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_USER=${DB_USER}
        - DB_DATABASE=${DB_DATABASE}
        - DB_VERSION=${DB_IMAGE_VERSION}
    ports:
      - ${DB_API_EXTERNAL_PORT}:${DB_API_INTERNAL_PORT}
    container_name: ${DB_CONTAINER_NAME}
  api:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile-api
      args:
        - PHP_VERSION=${PHP_VERSION}
    volumes:
      - ${API_LOCALE_VOLUME_PATH}:${API_TARGET_VOLUME_PATH}:${API_VOLUME_MODE}
    depends_on:
      - api_db
    container_name: ${API_CONTAINER_NAME}
  nginx:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile-nginx
      args:
        - NGINX_VERSION=${NGINX_VERSION}
    volumes:
      - ${API_LOCALE_VOLUME_PATH}:${NGINX_API_TARGET_VOLUME_PATH}:${NGINX_API_VOLUME_MODE}
    ports:
      - ${NGINX_API_EXTERNAL_PORT}:${NGINX_API_INTERNAL_PORT}
    command: [ nginx-debug, '-g', 'daemon off;' ]
    depends_on:
      - api
    container_name: ${NGINX_CONTAINER_NAME}
