version: "3.9"

services:
  postgres:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile-postgres
      args:
        - DB_PASSWORD=${DB_PASSWORD}
        - DB_USER=${DB_USER}
        - DB_DATABASE=${DB_DATABASE}

  api:
    build:
      context: .
      dockerfile: Dockerfile-php
    volumes:
       - ./api:/usr/local/var/www/api
    depends_on:
      - postgres