version: "3.9"

services:
  api_db:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile-apidb
      args:
        - DB_PASSWORD=${DB_API_PASSWORD}
        - DB_USER=${DB_API_USER}
        - DB_DATABASE=${DB_API_DATABASE}
        - DB_VERSION=${DB_IMAGE_VERSION}
    ports:
      - ${DB_API_EXTERNAL_PORT}:${DB_API_INTERNAL_PORT}
    container_name: ${DB_API_CONTAINER_NAME}

  api:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile-api
      args:
        - PHP_VERSION=${PHP_VERSION}
    volumes:
      - ${API_LOCALE_VOLUME_PATH}:${API_TARGET_VOLUME_PATH}:${API_VOLUME_MODE}
    depends_on:
      - api_db
    container_name: ${API_CONTAINER_NAME}

  auth_db:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile-authdb
      args:
        - DB_PASSWORD=${DB_AUTH_PASSWORD}
        - DB_USER=${DB_AUTH_USER}
        - DB_DATABASE=${DB_AUTH_DATABASE}
        - DB_VERSION=${DB_IMAGE_VERSION}
    ports:
      - ${DB_AUTH_EXTERNAL_PORT}:${DB_AUTH_INTERNAL_PORT}
    container_name: ${DB_AUTH_CONTAINER_NAME}

  auth:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile-auth
      args:
        - PHP_VERSION=${PHP_VERSION}
    volumes:
      - ${AUTH_LOCALE_VOLUME_PATH}:${AUTH_TARGET_VOLUME_PATH}:${AUTH_VOLUME_MODE}
    depends_on:
      - auth_db
    container_name: ${AUTH_CONTAINER_NAME}

  nginx:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile-nginx
      args:
        - NGINX_VERSION=${NGINX_VERSION}
    volumes:
      - ${API_LOCALE_VOLUME_PATH}:${NGINX_API_TARGET_VOLUME_PATH}:${NGINX_API_VOLUME_MODE}
      - ${AUTH_LOCALE_VOLUME_PATH}:${NGINX_AUTH_TARGET_VOLUME_PATH}:${NGINX_AUTH_VOLUME_MODE}
      - ./default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${NGINX_API_EXTERNAL_PORT}:${NGINX_API_INTERNAL_PORT}
      - ${NGINX_AUTH_EXTERNAL_PORT}:${NGINX_AUTH_INTERNAL_PORT}
    command: [ nginx-debug, '-g', 'daemon off;' ]
    depends_on:
      - api
      - auth
    container_name: ${NGINX_CONTAINER_NAME}
