FROM php:fpm-alpine3.14

ARG LOCAL_PROJECT_PATH

RUN apk add --no-cache $PHPIZE_DEPS

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/etc/php --filename=composer creates=/usr/local/etc/php/composer warn=no

RUN pecl install xdebug
RUN docker-php-ext-enable xdebug \
    && echo "zend_extension=$(find /usr/local/lib/php/extensions/ -name xdebug.so)" > /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "zend_extension=/usr/local/lib/php/extensions/no-debug-non-zts-20200930/xdebug.so" > /usr/local/etc/php/conf.d/php.ini \
    && echo "xdebug.remote_enable=on" >> /usr/local/etc/php/conf.d/xdebug.ini \
    && echo "xdebug.remote_autostart=on" >> /usr/local/etc/php/conf.d/xdebug.ini

WORKDIR /usr/local/var/www/

COPY ./api ./api