version: "3.9"

services:
  api_db:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    env_file:
      - ./api/.env

  api:
    build:
      context: .
      dockerfile: Dockerfile-symfony
      args:
        - CONTENT_SOURCE_PATH=./api
        - CONTENT_TARGET_PATH=/usr/local/var/www/api
    volumes:
      - ./api:/usr/local/var/www/api
    depends_on:
      - api_db

  nginx:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile-nginx
      args:
        - CONTENT_API_SOURCE_PATH=./api
        - CONTENT_API_TARGET_PATH=/usr/share/nginx/html/api
    volumes:
      - ./api:/usr/share/nginx/html/api:ro
    depends_on:
      - api